name: recovery_app
description: "A new Flutter project."
publish_to: 'none' 

version: 1.0.0+1

environment:
  sdk: ^3.11.0-93.2.beta

dependencies:
  flutter:
    sdk: flutter

  cupertino_icons: ^1.0.8
  firebase_core: ^4.3.0
  firebase_auth: ^6.1.3
  cloud_firestore: ^6.1.1
  flutter_riverpod: ^3.0.3
  flutter_map: ^8.2.2
  fl_chart: ^1.1.1
  google_generative_ai: ^0.4.7
  intl: ^0.20.2
  latlong2: ^0.9.1
  url_launcher: ^6.3.2
  geolocator: ^14.0.2
  shared_preferences: ^2.2.2
  http: ^1.2.0

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^6.0.0
  flutter_launcher_icons: ^0.14.2

flutter_icons:
  android: "launcher_icon"
  ios: true
  image_path: "assets/logo.png"
  min_sdk_android: 21 # android min sdk min:16, default 21

flutter:
  uses-material-design: true
  assets:
    - assets/logo.png
